### ISSUE TITLE
Git branching for handling staggered releases

### ISSUE THREAD

**Issue by gotoplanb** [Mobiquity/team-blog#31]
Talking with Rob Goff about how to update the git-flow branching model to better facilitate Build and Support work. Need to rethink http://nvie.com/posts/a-successful-git-branching-model/

Scenario: 

* prod bug found in `release/1.0` or could just be a change request
* Support creates `release/1.0.1` for the maintenance release with `release/1.0` as base
* create `support/1.0.1/JIRA-123` to complete the needed Support work
* open pr into `release/1.0.1` and open pr into `develop` as opposed to typical merge to `develop` then having to use a label or comment to remind to cherrypick into a release
* ? who deletes this support branch since there are two prs?

Other considerations:

* QA builds should either be manual trigger from `develop` or we should use `master` or `qa` branch name to indicate ready for QA testing. Goal is to keep partially complete work from getting premature QA, but we also want Build devs to merge into `develop` as soon as possible to mitigate unnecessary merge conflicts
* Jenkins RC builds should be started with parametized build config that explicitly states the release branch to use. This allows different countries to use different releases.

**Comment by rgoff** [comment]
Per your scenario:

The `support/1.0.1/JIRA-123` branch would probably be deleted by Build devs after merge to `develop`, or if they determined that code was not required. (For example, fix superseded by new/modified feature in new build project.)

**Comment by rgoff** [comment]
Will also need to think through parallel `qa` branches for Build and Support, and parameterized build configurations for the parallel branches. We should avoid having Build QA teams receiving Support QA builds, and vice versa.

**Comment by gotoplanb** [comment]
`patch` prefixing. JIRA cloned tickets for all different merge targets

**Comment by gotoplanb** [comment]
moved
